export default {
  ic_app_logo: require("../../assets/Icons/ic_app_logo.png"),
  ic_app_logo_small: require("../../assets/Icons/ic_app_logo_small.png"),
  ic_back_primary: require("../../assets/Icons/ic_back_primary.png"),
  ic_shopping_bag: require("../../assets/Icons/ic_shopping_bag.png"),
  ic_onboarding1: require("../../assets/Icons/ic_onboarding1.png"),
  ic_onboarding2: require("../../assets/Icons/ic_onboarding2.png"),
  ic_onboarding3: require("../../assets/Icons/ic_onboarding3.png"),
  ic_notification: require("../../assets/Icons/ic_notification.png"),
  ic_menu: require("../../assets/Icons/ic_menu.png"),
  ic_apple: require("../../assets/Icons/ic_apple.png"),
  ic_facebook: require("../../assets/Icons/ic_facebook.png"),
  ic_google: require("../../assets/Icons/ic_google.png"),
  ic_camera: require("../../assets/Icons/ic_camera.png"),
  ic_demo: require("../../assets/DemoImage/ic_demo.png"),
  ic_wish_list_unfill: require("../../assets/Icons/ic_wish_list_unfill.png"),
  ic_wish_list_fill: require("../../assets/Icons/ic_wish_list_fill.png"),
  ic_download: require("../../assets/Icons/ic_download.png"),
  ic_thumb: require("../../assets/Icons/ic_thumb.png"),
  ic_message: require("../../assets/Icons/ic_message.png"),
  ic_call: require("../../assets/Icons/ic_call.png"),
  ic_location: require("../../assets/Icons/ic_location.png"),
  ic_like: require("../../assets/Icons/ic_like.png"),
  ic_search: require("../../assets/Icons/ic_search.png"),
  ic_right_arrow: require("../../assets/Icons/ic_right_arrow.png"),
  ic_down_arrow: require("../../assets/Icons/ic_down_arrow.png"),
  ic_close: require("../../assets/Icons/ic_close.png"),
  ic_post: require("../../assets/Icons/ic_post.png"),
  ic_arrow_rigth: require("../../assets/Icons/ic_arrow_rigth.png"),
  ic_arrow_down: require("../../assets/Icons/ic_arrow_down.png"),
  ic_arrow_up: require("../../assets/Icons/ic_arrow_up.png"),
  ic_radio_checked: require("../../assets/Icons/ic_radio_checked.png"),
  ic_radio_unchecked: require("../../assets/Icons/ic_radio_unchecked.png"),
  bottom_background: require("../../assets/Icons/bottom_background.png"),
  ic_map_info_user: require("../../assets/Icons/ic_map_info_user.png"),
  ic_marker: require("../../assets/Icons/marker-icon.png"),

  ic_home: require("../../assets/Icons/ic_home.png"),
  ic_wishlist: require("../../assets/Icons/ic_wishlist.png"),
  ic_user: require("../../assets/Icons/ic_user.png"),
  ic_checkbox_unchecked: require("../../assets/Icons/ic_checkbox_unchecked.png"),
  ic_checkbox_checked: require("../../assets/Icons/ic_checkbox_checked.png"),

  ic_acc_business: require("../../assets/Icons/ic_acc_business.png"),
  ic_acc_user: require("../../assets/Icons/ic_acc_user.png"),

  ic_star: require("../../assets/Icons/ic_star.png"),
  ic_upload: require("../../assets/Icons/ic_upload.png"),
  ic_thumb_white: require("../../assets/Icons/ic_thumb_white.png"),
  ic_thumb_down_white: require("../../assets/Icons/ic_thumb_down_white.png"),
  ic_checkbox_uncheked: require("../../assets/Icons/ic_checkbox_uncheked.png"),
  ic_zoom_in_map: require("../../assets/Icons/ic_zoom_in_map.png"),
  ic_zoom_out_map: require("../../assets/Icons/ic_zoom_out_map.png"),
  ic_marker_new: require("../../assets/DemoImage/ic_marker_new.png"),
  ic_la: require("../../assets/Icons/ic_la.png"),
  ic_gallary: require("../../assets/Icons/ic_gallary.png"),
  plus: require("../../assets/Icons/plus.png"),
  
};
