// login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_LOADING = "LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

//registration
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

//State
export const GET_STATE_LOADING = "GET_STATE_LOADING";
export const GET_STATE_SUCCESS = "GET_STATE_SUCCESS";
export const GET_STATE_ERROR = "GET_STATE_ERROR";

//Main Category

export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

export const VIEW_ITEM_LOADING = "VIEW_ITEM_LOADING";
export const VIEW_ITEM_SUCCESS = "VIEW_ITEM_SUCCESS";
export const VIEW_ITEM_ERROR = "VIEW_ITEM_ERROR";
export const VIEW_ITEM_CLEAR = "VIEW_ITEM_CLEAR";

export const SEARCH_ITEM_LOADING = "SEARCH_ITEM_LOADING";
export const SEARCH_ITEM_SUCCESS = "SEARCH_ITEM_SUCCESS";
export const SEARCH_ITEM_ERROR = "SEARCH_ITEM_ERROR";
export const SEARCH_ITEM_CLEAR = "SEARCH_ITEM_CLEAR";

export const NOTIFICATION_ITEM_LOADING = "NOTIFICATION_ITEM_LOADING";
export const NOTIFICATION_ITEM_SUCCESS = "NOTIFICATION_ITEM_SUCCESS";
export const NOTIFICATION_ITEM_ERROR = "NOTIFICATION_ITEM_ERROR";
export const NOTIFICATION_ITEM_CLEAR = "NOTIFICATION_ITEM_CLEAR";

export const USER_LOGGED_OUT = "export USER_LOGGED_OUT";
